app/mod_search/views.py
from app.mod_projects.queries import get_project_name, get_project_id_by_name, get_user_rel_by_project_id, \
    get_projects_by_user, get_tx_by_gene_id
from app.mod_panels.queries import get_virtual_panels_by_panel_id, get_current_version, \
    get_genes_by_panelid, get_project_id_by_panel_id, get_current_version_vp, get_genes_by_vpanelid, \
    get_panels_by_project_id
from app.queries import get_gene_id_from_name
from flask import Blueprint
from flask import render_template, request, jsonify
from flask_login import login_required
from forms import *

from app.panel_pal import s
from flask_table import Table, Col, LinkCol
from queries import *

search = Blueprint('search', __name__, template_folder='templates')

class ItemTableSearchTx(Table):
    id = Col('Transcript Accession')

class ItemTableSearchGene(Table):
    gene_name = Col('Gene')

class ItemTableSearchVPanels(Table):
    panel_name = LinkCol('Panel', 'panels.view_panel', url_kwargs=dict(id='panel_id'), attr='panel_name')
    vpanel_name = LinkCol('Virtual Panel', 'panels.view_vpanel', url_kwargs=dict(id='vpanel_id'), attr='vpanel_name')

class ItemTableSearchVPanelsTwo(Table):
    vpanel_name = LinkCol('', 'panels.view_vpanel', url_kwargs=dict(id='vpanel_id'), attr='vpanel_name')

class ItemTableSearchPanels(Table):
    panel_name = LinkCol('', 'panels.view_panel', url_kwargs=dict(id='panel_id'), attr='panel_name')

class ItemTableSearchProjects(Table):
    project_name = LinkCol('', 'panels.view_panels', url_kwargs=dict(id='project_id'), attr='project_name')

class ItemTableSearchUsers(Table):
    username = Col('')

@search.route('/autocomplete_tx', methods=['GET'])
def autocomplete_tx():
    """
    this is the method for gene auto-completion - gets gene list from db and makes it into a json so that javascript can read it
    :return: jsonified gene list
    """
    value = str(request.args.get('q'))
    result = s.query(Tx).filter(Tx.accession.like("%" + value + "%")).all()
    data = [i.accession for i in result]
    return jsonify(matching_results=data)

@search.route('/autocomplete_panel', methods=['GET'])
def autocomplete_panel():
    """
    this is the method for gene auto-completion - gets gene list from db and makes it into a json so that javascript can read it
    :return: jsonified gene list
    """
    value = str(request.args.get('q'))
    result = s.query(Panels).filter(Panels.name.like("%" + value + "%")).all()
    data = [i.name for i in result]
    return jsonify(matching_results=data)

@search.route('/autocomplete_vp', methods=['GET'])
def autocomplete_vp():
    """
    this is the method for gene auto-completion - gets gene list from db and makes it into a json so that javascript can read it
    :return: jsonified gene list
    """
    value = str(request.args.get('q'))
    result = s.query(VirtualPanels).filter(VirtualPanels.name.like("%" + value + "%")).all()
    data = [i.name for i in result]
    return jsonify(matching_results=data)

@search.route('/autocomplete_project', methods=['GET'])
def autocomplete_project():
    """
    this is the method for gene auto-completion - gets gene list from db and makes it into a json so that javascript can read it
    :return: jsonified gene list
    """
    value = str(request.args.get('q'))
    result = s.query(Projects).filter(Projects.name.like("%" + value + "%")).all()
    data = [i.name for i in result]
    return jsonify(matching_results=data)

@search.route('/autocomplete_user', methods=['GET'])
def autocomplete_user():
    """
    this is the method for gene auto-completion - gets gene list from db and makes it into a json so that javascript can read it
    :return: jsonified gene list
    """
    value = str(request.args.get('q'))
    result = s.query(Users).filter(Users.username.like("%" + value + "%")).all()
    data = [i.username for i in result]
    return jsonify(matching_results=data)

@search.route('/', methods=['GET', 'POST'])
@login_required
def search_for():
    form = Search()
    if request.method == 'GET':
        return render_template("search.html", form=form)
    else:
        type = request.form["tables"]
        term = request.form["search_term"]

        if type == "Genes":
            tx_result=[]
            gene_id = get_gene_id_from_name(s, term)
            if gene_id:
                tx = get_tx_by_gene_id(s, gene_id)

                for t in tx:
                    tx_accession = {'id':t[1]}
                    tx_result.append(tx_accession)
                table_one = ItemTableSearchTx(tx_result, classes=['table', 'table-striped'])

                vpanel_result = []
                vpanel = get_vpanel_by_gene_id(s, gene_id)
                vpanel_list = list(vpanel)

                if len(vpanel_list) > 0:
                    for vp in vpanel_list:
                        vp_id = vp[0]
                        vp_name = vp[1]
                        broad_name = get_panel_by_vpanel_id(s, vp_id)
                        for b in broad_name:
                            vpanel_info = {'vpanel_name': vp_name, 'vpanel_id': vp_id, 'panel_name': b[0], 'panel_id': b[1]}
                            vpanel_result.append(vpanel_info)
                    table_two = ItemTableSearchVPanels(vpanel_result, classes=['table', 'table-striped'])
                else:
                    panel_results=[]
                    panel = get_panel_by_gene_id(s, gene_id)
                    for p in panel:
                        p_info = {'panel_name':p[1], 'panel_id':p[0]}
                        panel_results.append(p_info)
                    table_two = ItemTableSearchPanels(panel_results, classes=['table', 'table-striped'])

                return render_template("search_results.html", genes_tx=table_one, genes_panels=table_two, term=term)

        if type == "Transcripts":
            tx_id = get_tx_id_from_name(s,term)
            if tx_id:
                gene = get_gene_from_tx(s, tx_id)
                gene_result=[]

                for g in gene:
                    gene_info = {'gene_name':g[0]}
                    gene_id = g[1]
                    gene_result.append(gene_info)
                table_one = ItemTableSearchGene(gene_result, classes=['table', 'table-striped'])

                vpanel_result = []
                vpanel = get_vpanel_by_gene_id(s, gene_id)
                vpanel_list = list(vpanel)
                if len(vpanel_list) > 0:
                    for vp in vpanel_list:
                        vp_id = vp[0]
                        vp_name = vp[1]
                        broad_name = get_panel_by_vpanel_id(s, vp_id)
                        for b in broad_name:
                            vpanel_info = {'vpanel_name': vp_name, 'vpanel_id': vp_id, 'panel_name': b[0], 'panel_id': b[1]}
                            vpanel_result.append(vpanel_info)
                    table_two = ItemTableSearchVPanels(vpanel_result, classes=['table', 'table-striped'])
                else:
                    panel_results=[]
                    panel = get_panel_by_gene_id(s, gene_id)
                    for p in panel:
                        p_info = {'panel_name':p[1], 'panel_id':p[0]}
                        panel_results.append(p_info)
                    table_two = ItemTableSearchPanels(panel_results, classes=['table', 'table-striped'])

                return render_template("search_results.html", tx_genes=table_one, tx_panels=table_two, term=term)

        if type == "Panels":
            panel = get_panel_id_by_name(s,term)
            p_list = list(panel)
            if len(p_list) > 0:
                panel_results=[]
                for p in p_list:
                    panel_id = p[0]
                    project_id = p[1]
                    panel_info = {'panel_name': term, 'panel_id': panel_id}
                    panel_results.append(panel_info)
                table_one = ItemTableSearchPanels(panel_results, classes=['table', 'table-striped'])

                project = get_project_name(s,project_id)
                project_results = [{'project_name': project, 'project_id': project_id}]
                table_two = ItemTableSearchProjects(project_results, classes=['table', 'table-striped'])

                vpanels = get_virtual_panels_by_panel_id(s, panel_id)
                vpanel_results=[]
                for vp in vpanels:
                    vpanel_info={'vpanel_name': vp[6], 'vpanel_id': vp[0]}
                    vpanel_results.append(vpanel_info)
                table_three = ItemTableSearchVPanelsTwo(vpanel_results, classes=['table', 'table-striped'])

                users = get_user_rel_by_project_id(s, project_id)
                user_results = []
                for u in users:
                    user_info = {'username': u[0]}
                    user_results.append(user_info)
                table_four = ItemTableSearchUsers(user_results, classes=['table', 'table-striped'])


                version = get_current_version(s, panel_id)
                genes = get_genes_by_panelid(s, panel_id, version)
                gene_results=[]
                for g in genes:
                    gene_info={'gene_name': g[0]}
                    gene_results.append(gene_info)
                table_five = ItemTableSearchGene(gene_results, classes=['table', 'table-striped'])

                return render_template("search_results.html", panels_panels=table_one, panels_projects=table_two, panels_vpanels=table_three, \
                                       panels_users=table_four, panels_genes=table_five, term=term)


        if type == "VPanels":
            vpanel_id = get_vpanel_id_by_name(s, term)
            v_list = list(vpanel_id)
            if len(v_list) > 0:
                for vp in v_list:
                    vpanel_id = vp[0]
                    vpanel_results=[{'vpanel_name': term, 'vpanel_id': vpanel_id}]
                table_one = ItemTableSearchVPanelsTwo(vpanel_results, classes=['table', 'table-striped'])

app/mod_search/templates/search.html
{% extends "layout.html" %}

{% block content %}

<form action="{{ url_for('search.search_for') }}" method="POST" class="form-create">
    <h2>Search</h2>

<div class="form-group">
    {{ form.tables.label }}
    {{ form.tables(class_="form-control") }}
</div>
<div class="form-group">
    {{ form.search_term.label }}
    {{ form.search_term(class_="form-control") }}

</div>
<div class="form-group">
        {{ form.submit(class_="btn btn-primary") }}
</div>
</form>
{% endblock %}

app/mod_search/templates/search_results.html
{% extends "layout.html" %}

{% block content %}

<form action="{{ url_for('search.search_for') }}" method="POST" class="form-create">
    <h2>Results for "{{ term }}"</h2>
    <br>
    {% if no_results %}
    <h3><strong>Oh man!</strong> There were no results for this search term</h3>

    {% endif %}

    {% if genes_tx %}
    <h5>Gene has these transcripts:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ genes_tx }}
        </div>
    </div>
    <br>
    <h5>Gene is present in these panels:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ genes_panels }}
        </div>
    </div>
    {% endif %}

    {% if tx_genes %}
    <h5>Transcript belongs to gene:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ tx_genes }}
        </div>
    </div>
    <br>
    <h5>Gene is present in these panels:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ tx_panels }}
        </div>
    </div>
    {% endif %}

    {% if panels_projects %}
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ panels_panels }}
        </div>
    </div>
    <br>
    <h5>Part of project:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ panels_projects }}
        </div>
    </div>
    <br>
    <h5>Contains the following virtual panels:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ panels_vpanels }}
        </div>
    </div>
    <br>
    <h5>Users with edit access:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ panels_users }}
        </div>
    </div>
    <br>
    <h5>Genes present in this panel:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ panels_genes }}
        </div>
    </div>
    {% endif %}

    {% if vpanels_projects %}
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ vpanels_vpanels }}
        </div>
    </div>
    <br>
    <h5>In panel:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ vpanels_panels }}
        </div>
    </div>
    <br>
    <h5>Part of project:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ vpanels_projects }}
        </div>
    </div>
    <br>
    <h5>Users with edit access:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ vpanels_users }}
        </div>
    </div>
    <br>
    <h5>Genes present in this panel:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ vpanels_genes }}
        </div>
    </div>
    {% endif %}

    {% if projects_project %}
    <h5>Project:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ projects_project }}
        </div>
    </div>
    <br>
    <h5>Project contains these panels:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ projects_panels }}
        </div>
    </div>
    <br>
    <h5>Users with edit access:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ projects_users }}
        </div>
    </div>
    <br>
    {% endif %}

    {% if users_projects %}
    <h5>User has access to these projects:</h5>
    <div class="row">
        <div class="col-md-12 white-bk">
            {{ users_projects }}
        </div>
    </div>
    {% endif %}

</form>
{% endblock %}