app/mod_admin/views.py
from collections import OrderedDict

from app.mod_admin.queries import *
from app.mod_panels.queries import  unlock_panel_query
from queries import check_if_admin, get_user_id_by_username, check_tx
from flask import Blueprint
from flask import render_template, request, url_for, redirect
from flask_login import login_required, login_user, logout_user, current_user, UserMixin
from functools import wraps

from app.panel_pal import s, app
from app.activedirectory import UserAuthentication
from app.mod_projects.queries import get_all_projects, get_projects_by_user, remove_user_project_rel_no_id, add_user_project_rel
from flask_table import Table, Col, LinkCol
from forms import UserForm, NewTxForm
from queries import create_user, toggle_admin_query

import requests
import xml.etree.ElementTree as elemtree
import os
import subprocess
from Bio import SeqIO

class ItemTableUsers(Table):
    username = Col('User')
    admin = Col('Admin')
    toggle_admin = LinkCol('Toggle Admin', 'admin.toggle_admin', url_kwargs=dict(id='id'))


class ItemTableLocked(Table):
    name = Col('Panel')
    username = Col('Locked By')
    toggle_lock = LinkCol('Toggle Lock', 'admin.toggle_locked', url_kwargs=dict(id='id'))

class User(UserMixin):
    """
    Defines methods for users for authentication. Each user has an id (username) and a password

    """
    def __init__(self, id, password=None):
        self.id = id
        self.password = password

    def is_authenticated(self, s, id, password):
        """
        Method to check if user is authenticated. The method checks the database for the username and then active
        directory for username and password authentication

        :param s: SQLAlechmy session token
        :param id: ID of the user (username)
        :param password: password the user has entered into the application
        :return: True if the user authenticates, false if not
        """
        validuser = get_user_by_username(s, id)
        if len(list(validuser)) == 0:
            return False
        else:
            check_activdir = UserAuthentication().authenticate(id, password)

            if check_activdir != "False":
                return True
            else:
                return False

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return self.id

admin = Blueprint('admin', __name__, template_folder='templates')

def admin_required(f):
    """
    This method allows others to require the user to have admin permissions to execute

    :param f:
    :return:
    """
    @wraps(f)
    def decorated_function(*args,**kwargs):
        if check_if_admin(s,current_user.id) is False:
            return redirect('/')
        return f(*args, **kwargs)
    return decorated_function

@admin.route('/user', methods=['GET', 'POST'])
@login_required
@admin_required
def user_admin():
    """
    view to allow users to be added and admin rights toggled

    :return: render html template
    """
    form = UserForm()
    message = None
    if request.method == 'POST':
        username = request.form["name"]
        if check_if_admin(s, current_user.id):
            create_user(s, username)
            message = "Added user: " + username
        else:
            return render_template('users.html', form=form, message="You can't do that")
    users = get_users(s)
    result = []
    for i in users:
        if i.username != current_user.id:
            row = dict(zip(i.keys(), i))
            result.append(row)
    table = ItemTableUsers(result, classes=['table', 'table-striped'])
    return render_template('users.html', form=form, table=table, message=message)


@admin.route('/user/toggle', methods=['GET', 'POST'])
@login_required
@admin_required
def toggle_admin():
    """
    toggles admin rights of a user

    :return: redirect to user_admin
    """
    user_id = request.args.get('id')
    toggle_admin_query(s, user_id)
    return redirect(url_for('admin.user_admin'))


@admin.route('/locked/toggle', methods=['GET', 'POST'])
@login_required
@admin_required
def toggle_locked():
    """
    toggles the locked status of a panel

    useful if someone has forgotten they have left a panel locked - an admin can unlock

    :return: view_locked method
    """
    panel_id = request.args.get('id')
    unlock_panel_query(s, panel_id)
    return view_locked(message="Panel Unlocked")


@admin.route('/logs', methods=['GET', 'POST'])
@login_required
@admin_required
def view_logs():
    """
    view admin logs so that you can see what users have been doing

    :return: render html template
    """
    if request.args.get('file'):
        log = request.args.get('file')
    else:
        log = '/tmp/PanelPal.log'

    import glob
    files = []
    listing = glob.glob('/tmp/PanelPal*log*')
    for filename in listing:
        files.append(filename)

    result = []
    with open(log) as f:
        for line in f:
            result.append(line.rstrip())

    return render_template('logs.html', log=result, files=files)


@admin.route('/locked', methods=['GET', 'POST'])
@login_required
@admin_required
def view_locked(message=None):
    """
    view locked panels

    :param message: message to display
    :return: rendered html template
    """
    locked = get_all_locked(s)
    result = []
    for i in locked:
        row = dict(zip(i.keys(), i))
        result.append(row)
    table = ItemTableLocked(result, classes=['table', 'table-striped'])
    return render_template('locked.html', table=table, message=message)


@admin.route("/permissions", methods=['GET', 'POST'])
@login_required
@admin_required
def edit_permissions_admin():
    """
    edit permissions of users to allow editing of panels belonging to projects

    :return: rendered html template
    """
    users = get_users(s)
    result = OrderedDict()
    message = None
    for i in users:
        username = get_username_by_user_id(s, i.id)
        result[username] = dict()
        user_projects = get_projects_by_user(s, username)
        all_projects = get_all_projects(s)
        for p in all_projects:
            result[username][p.id] = {'name': p.name, 'checked': ''}
        for u in user_projects:
            result[username][u.id] = {'name': u.name, 'checked': 'checked'}

    if request.method == 'POST':
        status = {}
        for i in request.form.getlist('check'):
            print i
            username, project_id = i.split("_")
            print username
            print status
            if username not in status:
                status[username] = list()
                status[username].append(int(project_id))
            else:
                status[username].append(int(project_id))
        message = "Your changes have been made"

        print status
        # find changes
        for username in result:
            print username
            for project_id in result[username]:
                checked = result[username][project_id]["checked"]
                name = result[username][project_id]["name"]
                if username in status:
                    if checked == "checked":
                        print status[username]
                        print project_id
                        if project_id in status[username]:
                            # this is OK it's checked and project
                            pass
                        else:
                            # not OK - it's been unchecked
                            print "username in but UNCHECKED"
                            remove_user_project_rel_no_id(s, username, project_id)
                    else:
                        if project_id in status[username]:
                            user_id = get_user_id_by_username(s, username)
                            add_user_project_rel(s, user_id, project_id)
                            print "NOW CHECKED"
                else:
                    if checked == "checked":
                        print "UNCHECKED"
                        remove_user_project_rel_no_id(s, username, project_id)

    users = get_users(s)
    result = OrderedDict()
    for i in users:
        username = get_username_by_user_id(s, i.id)
        result[username] = dict()
        user_projects = get_projects_by_user(s, username)
        all_projects = get_all_projects(s)
        for p in all_projects:
            row = dict(zip(p.keys(), p))
            result[username][p.id] = {'name': p.name, 'checked': ''}
        for u in user_projects:
            result[username][u.id] = {'name': u.name, 'checked': 'checked'}

    return render_template("permissions_admin.html", permissions=result, message=message)

@admin.route("/FAQ", methods=["GET", "POST"])
def faq_page():
    """
    Displays the FAQs for PanelPal

    :return: render FAQ template
    """
    return render_template("faq.html")

def get_fasta(acc, retry=False):
    """

    :param acc:
    :param retry:
    :return:
    """
    acc_id_url = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=nucleotide&term=' + acc + '%5Baccession%5D'
    print(acc_id_url)
    acc_id_response = requests.get(acc_id_url)

    acc_xml = elemtree.fromstring(acc_id_response.text)
    count = int(acc_xml.find('Count').text)
    if count == 0 and not retry:
        base_acc, version = acc.split('.')
        new_version = int(version) + 1
        new_acc = base_acc + '.' + str(new_version)
        print('No results returned, trying new version ' + new_acc)
        return get_fasta(new_acc, True)
    else:
        acc_id = acc_xml.find('IdList').find('Id').text

    genbank_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=" + acc_id + "&rettype=fasta"
    genbank_response = requests.get(genbank_url)
    basedir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
    file_name = basedir + '/resources/' + acc + '.fa'
    f = open(file_name, 'w')
    try:

app/templates/about.html
{% extends "layout.html" %}

{% block content %}
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-12"><h2><span class="glyphicon glyphicon-th-list"></span> PanelPal Development Team</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                Developed at Sheffield Diagnostic Genetics Service by the Bioinformatics team:
                <ul>
                    <li>Matthew Parker</li>
                    <li>Natalie Groves</li>
                    <li>Elizabeth Sollars</li>
                    <li>Nichola Cooper</li>
                    <li>Christine Hicks</li>
                </ul>
            </div>
            <div class="col-md-6"><img class="img-thumbnail" src="static/images/bioinfo.jpg"></div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/home.html
{% extends "layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1><span class="glyphicon glyphicon-th-list"></span> Welcome to PanelPal!</h1>
    <p>This web application allows creation of gene panels for next generation sequencing. It also provides an API which
        allows integration into NGS pipelines</p>
    <p><a href="{{url_for('panels.create_panel_process')}}" class="btn btn-default btn-lg">
        <span class="glyphicon glyphicon-pencil"></span> Create Your 1st Panel
    </a></p>
    {% if browser == 'msie' %}
    <p>

        Using internet explorer? Go to the <a
            href="{{url_for('admin.faq_page')}}" target="_top">FAQ</a> page for display instructions</p>
    {% endif %}
    Need to register? Email your windows login name to <a
        href="mailto:matthewparker24+lzj6vkpuibpnivi6nsog@boards.trello.com?Subject=#PanelPal%20#registration%20New%20login"
        target="_top">bioinformatics</a>
    <br/>
    Need to report a bug? Email a ticket to <a
        href="mailto:matthewparker24+lzj6vkpuibpnivi6nsog@boards.trello.com?Subject=#PanelPal%20#bugreport%20PanelPal%20bug"
        target="_top">bioinformatics</a>
</div>


{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    {{ JSGlue.include() }}

    <title>PanelPal</title>

    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/jquery-1.12.4.js"></script>
    <script src="/static/js/jquery-ui.js"></script>
    <script src="/static/js/jquery.dataTables.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="/static/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="/static/css/jquery-ui.css">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/respond.src.js"></script>
    <link rel="stylesheet" href="/static/css/panel_pal.css">
    <script type="text/javascript" language="javascript" src="/static/js/dataTables.bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

    <!--<link rel="stylesheet" href="/static/css/font-awesome.min.css">-->

    <script src="/static/js/panelpal.js"></script>

    <!--<script type="text/javascript">-->
    <!--$(document).ready(function () {-->
    <!--$('#panel').DataTable({-->
    <!--"pageLength": 10,-->
    <!--"data": "{{ table|safe }}",-->
    <!--"columns": [{"title": "Chr"},-->
    <!--{"title": "Start"},-->
    <!--{"title": "End"},-->
    <!--{"title": "Gene"},-->
    <!--{"title": "Region Name"}-->
    <!--]-->
    <!--});-->
    <!--});-->

    <!--</script>-->

    {% if table %}
    <script type="text/javascript">
        //        var dataSet = "{{ table|safe }}"
        $(document).ready(function () {
            $('#panel').DataTable({
                "pageLength": 10,
                data: {{ table | safe }},
                "aoColumns":[
                            {title: "Chr", sWidth: '90px'},
                            {title: "Start", sWidth: '90px'},
                            {title: "End", sWidth: '90px'},
                            {title: "Gene", sWidth: '90px'},
                            {title: "Region Name", sWidth: '150px'}
                            ]
        });
        });


    </script>
    {% endif %}

    {% if delete == True %}
    <script type="text/javascript">


        $(document).ready(function () {

            $('#areyousure').modal('show');

        });
    </script>
    {% endif %}
</head>


<body>
<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="ajaxModal" role="dialog">
        <div class="modal-dialog vertical-align-center">

            <!-- Modal content-->
            <div id="error" class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Well this is embarrassing...</h4>
                </div>
                <div class="modal-body">
                    <p>Something has gone wrong here, if the problem persists please contact a member of the
                        bioinformatics team.</p>
                </div>
                <div class="modal-footer" id="trace">
                </div>
            </div>


        </div>

    </div>
    <div class="modal fade" id="regionModal" role="dialog">
        <div class="modal-dialog vertical-align-center">
            <div id="region_change" class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Uh-oh!</h4>
                </div>
                <div class="modal-body">
                    <p>That region can't be updated.</p>
                    <p>Please make sure that the start value is smaller than the end value for the region</p>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="cdsModal" role="dialog">
        <div class="modal-dialog vertical-align-center">
            <div id="region_cds" class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Hmmmm...</h4>
                </div>
                <div class="modal-body">
                    <p>That region no longer covers the coding region.</p>
                    <p>Are you sure you want to change it?</p>
                </div>
                <div class="modal-footer">
                    <ul class="list-unstyled list-inline pull-right">
                        <li>
                            <button type="button" class="btn btn-default" id="region-ok" data-dismiss="modal">Yes</button>
                        </li>
                        <li>
                            <button type="button" class="btn btn-default" id="region-cancel" data-dismiss="modal">No</button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


</div>

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button><!---->
            <a class="navbar-brand" href="{{ url_for('index') }}"><span
                    class="glyphicon glyphicon-th-list"></span>
                PanelPal</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('search.search_for') }}">Search</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true"
                       aria-expanded="false">Projects <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('projects.view_projects') }}">View Projects</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ url_for('projects.add_projects') }}">Create Project</a></li>
                    </ul>
                </li>


                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true"
                       aria-expanded="false">Panels <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('panels.view_panels') }}">View Panels</a></li>
                        <li><a href="{{ url_for('panels.create_panel_process') }}">Create Panel</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ url_for('panels.manage_locked') }}">Manage Locked Panels</a></li>
                        <!--<li><a href="#">Create Panel From Panel App</a></li>-->
                        <!--<li role="separator" class="divider"></li>-->
                        <!--<li><a href="#">Export Panel</a></li>-->
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true"
                       aria-expanded="false">Virtual Panels <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('panels.view_virtual_panels') }}">View Virtual Panels</a></li>
                        <li><a href="{{ url_for('panels.create_virtual_panel_process') }}">Create a Virtual
                            Panel</a>
                        </li>
                        <!--<li role="separator" class="divider"></li>-->
                        <!--<li><a href="#">Export Virtual Panel</a></li>-->
                    </ul>
                </li>
                {% if admin == True %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true"
                       aria-expanded="false">Admin <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/admin/user">User Admin</a></li>
                        <li><a href="/admin/permissions">Permissions</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/admin/logs">Logs</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/admin/locked">Locked</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/admin/new-tx">Add New Tx</a></li>
                    </ul>
                </li>
                {% endif %}

                <li><a href="/api/spec.html"><span class="glyphicon glyphicon-cog"></span> API</a></li>
                <li><a href="{{ url_for('admin.faq_page') }}"><span class="glyphicon glyphicon-question-sign"></span> FAQ</a></li>

            <li>
            <form class="navbar-form navbar-right" role="search">
                {% if logged_in == True %}
                <a href="{{ url_for('logout')}}" class="btn btn-success">Logout <strong>{{ userid
                    }}</strong></a>
                {% else %}
                <a href="{{ url_for('login')}}" class="btn btn-primary">Login</a>
                {% endif %}
            </form>
            </li>
            </ul>
        </div>
    </div>
</nav>

{% block popup %}
{% endblock %}

<div class="container theme-showcase" role="">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</div>


</body>
</html>

app/templates/locked.html
{% extends "layout.html" %}

{% block content %}

<h2>Locked Panels</h2>
<div class="row bttm-buffer">



    <div class="col-md-12">
           {% if message %}
<div class="alert alert-success" id="message"><strong>FYI</strong> {{ message }}</div>
{% endif %}
        </div>
    </div>


<div class="row bttm-buffer">



    <div class="col-md-12">
        {{ table }}
        </div>
    </div>


{% endblock %}

app/templates/login.html
{% extends "layout.html" %}

{% block content %}
<div class="wrapper">
    <form action="{{ url_for('login') }}" method="POST" class="form-signin">


        <h2>Login</h2><br>


        {% if message %}
        <div class="alert alert-danger"><strong>{{ modifier }}</strong> {{ message }}</div>
        {% endif %}

        <div class="form-group">
            {{ form.username.label }}
            {{ form.username(class_="form-control") }}
        </div>
        <div class="form-group">
            {{ form.password.label }}
            {{ form.password(class_="form-control") }}
            {{ form.next(class_="form-control") }}
        </div>
        <div class="form-group">
            {{ form.submit(class_="btn btn-primary") }}
        </div>
        Need to register? email <a
        href="mailto:matthewparker24+lzj6vkpuibpnivi6nsog@boards.trello.com?Subject=#PanelPal%20#registration%20New%20login"
        target="_top">bioinformatics</a>
    </form>
</div>

{% endblock %}

app/templates/logs.html
{% extends "layout.html" %}

{% block content %}
<h2>Action Logs</h2>
<h3>Available Logs</h3>
<div class="row bttm-buffer">
    <div class="col-md-12">
        {% for i in files %}

        <a href="{{ url_for('view_logs',file=i ) }}">{{ i }}</a><br>

        {% endfor %}
    </div>
</div>
<div class="row top-buffer bttm-buffer">
    <div class="col-md-12">
        <div class="pre-scrollable logs">


            {% for i in log %}

            {{ i }}<br>

            {% endfor %}

        </div>
    </div>


    {% endblock %}

app/templates/permissions_admin.html
{% extends "layout.html" %}

{% block content %}

<div class="wrapper">
<form action="{{ url_for('edit_permissions_admin') }}" method="POST" class="form-permissions">
    <h2>Edit User Permissions</h2><br>
    {% if message %}
<div class="alert alert-success" id="message"><strong>FYI</strong> {{ message }}</div>
{% endif %}
    Tick boxes and click "Submit Changes" to give users permission to certain projects.<br><br>
    <table class="table table-striped">
        <thead>
        <th>
            User
        </th>
        <th>
            Projects
        </th>

        </thead>
        {% for username in permissions %}
        <tr>
            <td>
                {{ username }}
            </td>
            <td>
                <div class="form-group">
                    {% for project_id in permissions[username] %}


                    <label>{{ permissions[username][project_id]["name"] }} </label>

                    <input value="{{username}}_{{project_id}}" name="check" id="checkbox" type="checkbox" {{
                           permissions[username][project_id]['checked'] }}>

                    {% endfor %}
                </div>
            </td>


        </tr>

        {% endfor %}

    </table>
        <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Submit Changes">
    </div>


</form>
</div>
{% endblock %}

app/templates/users.html
{% extends "layout.html" %}
 
{% block content %}

<div class="wrapper">

  <form action="{{ url_for('user_admin') }}" method="POST" class="form-create" >

    <h2>Add User</h2>


    {% for message in form.name.errors %}
  <div class="alert alert-danger">Oh Snap! {{ message }}</div>
{% endfor %}
     {% if message %}
<div class="alert alert-success" id="message"><strong>FYI</strong> {{ message }}</div>
{% endif %}

    {{ form.hidden_tag() }}
    <div class="form-group">
    {{ form.name.label }}
    {{ form.name(class_="form-control") }}
    </div>
    {{ form.submit(class_="btn btn-primary") }}

      <h2>Users</h2>
<div class="white-bk">
{{ table }}
</div>
  </form>




</div>

 {% endblock %}

app/templates/users_add.html
{% extends "layout.html" %}
 
{% block content %}
  <h2>Add User</h2>

  <form action="{{ url_for('worklist') }}" method="POST" class="form">
    {{ form.hidden_tag() }}
    <div class="form-group">

          {% for message in form.name.errors %}
  <div class="alert alert-danger">Oh Snap! {{ message }}</div>
{% endfor %}

   {% if message %}
<div class="alert alert-success" id="message"><strong>FYI</strong> {{ message }}</div>
{% endif %}

    {{ form.name.label }}
    {{ form.name(class_="form-control") }}
    </div>
    {{ form.submit(class_="btn btn-primary") }}
  </form>
{% endblock %}